### ISSUE TITLE
Example not running

### ISSUE THREAD

**Issue by Graham-McCracken** [JohnCoene/shinytitle#1]
This seems like a useful package. 

For some reason, I obtain the following error upon running your example:

"Error: 'use_shinytitle' is not an exported object from 'namespace:shinytitle'".

Any help appreciated. 

Thank you.

**Comment by JohnCoene** [comment]
Are you sure you installed the package?

```r
install.packages("remotes")
remotes::install_github("JohnCoene/shinytitle")
```

**Comment by Graham-McCracken** [comment]
Hi John,

Yes, I had installed it, but the error persisted.

Thanks for checking it out,
Graham

**Comment by JohnCoene** [comment]
I'll assume it's running and close this. Feel free to reopen.
